local M = {}

M.get_highlights = function()
	return {
		NeoTreeDirectoryIconSrc = { fg = "#42A5F5" },
		NeoTreeDirectoryIconRoutes = { fg = "#FF7043" },
		NeoTreeDirectoryIconComponents = { fg = "#EC407A" },
		NeoTreeDirectoryIconNodeModules = { fg = "#8BC34A" },
		NeoTreeDirectoryIconPackage = { fg = "#8BC34A" },
		NeoTreeDirectoryIconTranslations = { fg = "#03A9F4" },
		NeoTreeDirectoryIconAssets = { fg = "#FFA726" },
		NeoTreeDirectoryIconPublic = { fg = "#66BB6A" },
		NeoTreeDirectoryIconTest = { fg = "#FF5252" },
		NeoTreeDirectoryIconConfig = { fg = "#7986CB" },
		NeoTreeDirectoryIconLib = { fg = "#FFB74D" },
		NeoTreeDirectoryIconTypes = { fg = "#26A69A" },
		NeoTreeDirectoryIconHooks = { fg = "#BA68C8" },
		NeoTreeDirectoryIconMiddleware = { fg = "#78909C" },
		NeoTreeDirectoryIconApi = { fg = "#4DB6AC" },
		NeoTreeDirectoryIconScripts = { fg = "#FFB74D" },
		NeoTreeDirectoryIconStyles = { fg = "#F06292" },
		NeoTreeDirectoryIconDocs = { fg = "#29B6F6" },
		NeoTreeDirectoryIconBuild = { fg = "#FFA000" },
		NeoTreeDirectoryIconDist = { fg = "#7E57C2" },
		NeoTreeDirectoryIconDatabase = { fg = "#EF5350" },
		NeoTreeDirectoryIconLogs = { fg = "#FF7043" },
		NeoTreeDirectoryIconTemp = { fg = "#90A4AE" },
		NeoTreeDirectoryIconCache = { fg = "#90A4AE" },
		NeoTreeDirectoryIconVendor = { fg = "#7986CB" },
		NeoTreeDirectoryIconPlugins = { fg = "#AB47BC" },
		NeoTreeDirectoryIconThemes = { fg = "#EC407A" },
		NeoTreeDirectoryIconBackup = { fg = "#8D6E63" },
		NeoTreeDirectoryIconImages = { fg = "#26A69A" },
		NeoTreeDirectoryIconMedia = { fg = "#26A69A" },
		NeoTreeDirectoryIconFonts = { fg = "#8BC34A" },
		NeoTreeDirectoryIconData = { fg = "#EF5350" },
		NeoTreeDirectoryIconMocks = { fg = "#FF7043" },
		NeoTreeDirectoryIconFixtures = { fg = "#FF7043" },
		NeoTreeDirectoryIconSeeds = { fg = "#8BC34A" },
		NeoTreeDirectoryIconMigrations = { fg = "#7986CB" },
		NeoTreeDirectoryIconHelpers = { fg = "#BA68C8" },
		NeoTreeDirectoryIconExtensions = { fg = "#7986CB" },
		NeoTreeDirectoryIconModules = { fg = "#7986CB" },
	}
end

M.get_folder_icons = function()
	return {
		[".git"] = { text = "", hl = "NeoTreeDirectoryIconNodeModules" },
		["src"] = { text = "󱂵", hl = "NeoTreeDirectoryIconSrc" },
		["source"] = { text = "󱂵", hl = "NeoTreeDirectoryIconSrc" },
		["routes"] = { text = "󰉒", hl = "NeoTreeDirectoryIconRoutes" },
		["route"] = { text = "󰉒", hl = "NeoTreeDirectoryIconRoutes" },
		["router"] = { text = "󰉒", hl = "NeoTreeDirectoryIconRoutes" },
		["pages"] = { text = "󰉒", hl = "NeoTreeDirectoryIconRoutes" },
		["components"] = { text = "󱧶", hl = "NeoTreeDirectoryIconComponents" },
		["node_modules"] = { text = "󰏗", hl = "NeoTreeDirectoryIconNodeModules" },
		["package"] = { text = "󰏗", hl = "NeoTreeDirectoryIconPackage" },
		["packages"] = { text = "󰏗", hl = "NeoTreeDirectoryIconPackage" },
		["i18next"] = { text = "󱉭", hl = "NeoTreeDirectoryIconTranslations" },
		["i18n"] = { text = "󱉭", hl = "NeoTreeDirectoryIconTranslations" },
		["translations"] = { text = "󱉭", hl = "NeoTreeDirectoryIconTranslations" },
		["locales"] = { text = "󱉭", hl = "NeoTreeDirectoryIconTranslations" },
		["locale"] = { text = "󱉭", hl = "NeoTreeDirectoryIconTranslations" },
		["assets"] = { text = "󰛫", hl = "NeoTreeDirectoryIconAssets" },
		["public"] = { text = "󰉑", hl = "NeoTreeDirectoryIconPublic" },
		["static"] = { text = "󰉐", hl = "NeoTreeDirectoryIconPublic" },
		["test"] = { text = "󰉕", hl = "NeoTreeDirectoryIconTest" },
		["tests"] = { text = "󰉕", hl = "NeoTreeDirectoryIconTest" },
		["__tests__"] = { text = "󰉕", hl = "NeoTreeDirectoryIconTest" },
		["config"] = { text = "󱁿", hl = "NeoTreeDirectoryIconConfig" },
		["configs"] = { text = "󱁿", hl = "NeoTreeDirectoryIconConfig" },
		["lib"] = { text = "󰉋", hl = "NeoTreeDirectoryIconLib" },
		["libs"] = { text = "󰉋", hl = "NeoTreeDirectoryIconLib" },
		["utils"] = { text = "󱧼", hl = "NeoTreeDirectoryIconLib" },
		["types"] = { text = "󰉌", hl = "NeoTreeDirectoryIconTypes" },
		["@types"] = { text = "󰉌", hl = "NeoTreeDirectoryIconTypes" },
		["hooks"] = { text = "󰚝", hl = "NeoTreeDirectoryIconHooks" },
		["middleware"] = { text = "󱧱", hl = "NeoTreeDirectoryIconMiddleware" },
		["api"] = { text = "󱧬", hl = "NeoTreeDirectoryIconApi" },
		["apis"] = { text = "󱧬", hl = "NeoTreeDirectoryIconApi" },
		["scripts"] = { text = "󰉋", hl = "NeoTreeDirectoryIconScripts" },
		["style"] = { text = "󰉏", hl = "NeoTreeDirectoryIconStyles" },
		["styles"] = { text = "󰉏", hl = "NeoTreeDirectoryIconStyles" },
		["css"] = { text = "󰉏", hl = "NeoTreeDirectoryIconStyles" },
		["docs"] = { text = "󰉔", hl = "NeoTreeDirectoryIconDocs" },
		["icons"] = { text = "󰉔", hl = "NeoTreeDirectoryIconDocs" },
		["doc"] = { text = "󰉔", hl = "NeoTreeDirectoryIconDocs" },
		["build"] = { text = "󰛨", hl = "NeoTreeDirectoryIconBuild" },
		["dist"] = { text = "󰏗", hl = "NeoTreeDirectoryIconDist" },
		["database"] = { text = "󰆼", hl = "NeoTreeDirectoryIconDatabase" },
		["db"] = { text = "󰆼", hl = "NeoTreeDirectoryIconDatabase" },
		["logs"] = { text = "󰌱", hl = "NeoTreeDirectoryIconLogs" },
		["log"] = { text = "󰌱", hl = "NeoTreeDirectoryIconLogs" },
		["temp"] = { text = "󰪶", hl = "NeoTreeDirectoryIconTemp" },
		["tmp"] = { text = "󰪶", hl = "NeoTreeDirectoryIconTemp" },
		["cache"] = { text = "󰆦", hl = "NeoTreeDirectoryIconCache" },
		["vendor"] = { text = "󰏗", hl = "NeoTreeDirectoryIconVendor" },
		["plugins"] = { text = "󰜫", hl = "NeoTreeDirectoryIconPlugins" },
		["themes"] = { text = "󰉏", hl = "NeoTreeDirectoryIconThemes" },
		["backup"] = { text = "󰁯", hl = "NeoTreeDirectoryIconBackup" },
		["images"] = { text = "󰈥", hl = "NeoTreeDirectoryIconImages" },
		["img"] = { text = "󰈥", hl = "NeoTreeDirectoryIconImages" },
		["media"] = { text = "󰈧", hl = "NeoTreeDirectoryIconMedia" },
		["fonts"] = { text = "󰛖", hl = "NeoTreeDirectoryIconFonts" },
		["font"] = { text = "󰛖", hl = "NeoTreeDirectoryIconFonts" },
		["data"] = { text = "󰆼", hl = "NeoTreeDirectoryIconData" },
		["mocks"] = { text = "󰌵", hl = "NeoTreeDirectoryIconMocks" },
		["fixtures"] = { text = "󰌵", hl = "NeoTreeDirectoryIconFixtures" },
		["seeds"] = { text = "󰊠", hl = "NeoTreeDirectoryIconSeeds" },
		["migrations"] = { text = "󰁨", hl = "NeoTreeDirectoryIconMigrations" },
		["helpers"] = { text = "󰍉", hl = "NeoTreeDirectoryIconHelpers" },
		["extensions"] = { text = "󰡱", hl = "NeoTreeDirectoryIconExtensions" },
		["modules"] = { text = "󰏗", hl = "NeoTreeDirectoryIconModules" },
	}
end

return M

